import{a as b,S as w,i as L}from"./assets/vendor-c3c9fc05.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const y of s.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&l(y)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const S="45272920-c2160489642e002ce9de87f86",$="https://pixabay.com/api/";async function m(t,r=1){const o=`${$}?key=${S}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${r}`,l=await b.get(o);if(l.status!==200)throw new Error("Network response was not ok");return l.data}let u;function h(t){const r=document.querySelector(".gallery");r.innerHTML=t.map(o=>`
        <a href="${o.largeImageURL}" class="gallery__item">
            <img src="${o.webformatURL}" alt="${o.tags}" class="gallery__image" />
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${o.likes}</p>
                <p class="info-item"><b>Views:</b> ${o.views}</p>
                <p class="info-item"><b>Comments:</b> ${o.comments}</p>
                <p class="info-item"><b>Downloads:</b> ${o.downloads}</p>
            </div>
        </a>
    `).join(""),u?u.refresh():u=new w(".gallery a")}function i(t,r="info"){L.show({message:t,position:"topRight",color:r})}function f(){const t=document.querySelector(".gallery");t.innerHTML=""}const g=document.querySelector("#search-form"),q=g.querySelector('input[name="searchQuery"]'),a=document.querySelector(".loader"),n=document.createElement("button");n.textContent="Load More";n.classList.add("btn","btn-secondary");n.style.display="none";document.body.appendChild(n);let d="",c=1,p=0;g.addEventListener("submit",async t=>{if(t.preventDefault(),d=q.value.trim(),c=1,d===""){i("Please enter a search query","error"),f(),n.style.display="none";return}f(),a.style.display="block";try{const r=await m(d,c);a.style.display="none",p=r.totalHits,r.hits.length===0?(i("Sorry, there are no images matching your search query. Please try again!","error"),n.style.display="none"):(h(r.hits),n.style.display=p>15?"block":"none")}catch{a.style.display="none",i("An error occurred. Please try again later.","error"),n.style.display="none"}});n.addEventListener("click",async()=>{c+=1,a.style.display="block";try{const t=await m(d,c);a.style.display="none",t.hits.length===0||c*15>=p?(i("Sorry, but you have reached the end of search results.","info"),n.style.display="none"):(h(t.hits),window.scrollBy({top:document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height*2,behavior:"smoth"}))}catch{a.style.display="none",i("An error occured. Please try again later.","error")}});
//# sourceMappingURL=commonHelpers.js.map
