import{a as b,S as w,i as L}from"./assets/vendor-c3c9fc05.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const y of s.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&r(y)}).observe(document,{childList:!0,subtree:!0});function l(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=l(e);fetch(e.href,s)}})();const $="45272920-c2160489642e002ce9de87f86",v="https://pixabay.com/api/";async function m(t,o=1){const l=`${v}?key=${$}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${o}`,r=await b.get(l);if(r.status!==200)throw new Error("Network response was not ok");return r.data}let u;function h(t){const o=document.querySelector(".gallery"),l=t.map(r=>`
        <a href="${r.largeImageURL}" class="gallery__item">
            <img src="${r.webformatURL}" alt="${r.tags}" class="gallery__image" />
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${r.likes}</p>
                <p class="info-item"><b>Views:</b> ${r.views}</p>
                <p class="info-item"><b>Comments:</b> ${r.comments}</p>
                <p class="info-item"><b>Downloads:</b> ${r.downloads}</p>
            </div>
        </a>
    `).join("");o.insertAdjacentHTML("beforeend",l),u?u.refresh():u=new w(".gallery a")}function i(t,o="info"){L.show({message:t,position:"topRight",color:o})}function f(){const t=document.querySelector(".gallery");t.innerHTML=""}const g=document.querySelector("#search-form"),S=g.querySelector('input[name="searchQuery"]'),a=document.querySelector(".loader"),n=document.createElement("button");n.textContent="Load more";n.classList.add("btn","btn-secondary");n.style.display="none";document.body.appendChild(n);let d="",c=1,p=0;g.addEventListener("submit",async t=>{if(t.preventDefault(),d=S.value.trim(),c=1,d===""){i("Please enter a search query","error"),f(),n.style.display="none";return}f(),a.style.display="block",n.style.display="none";try{const o=await m(d,c);a.style.display="none",p=o.totalHits,o.hits.length===0?(i("Sorry, no images found. Please try again!","error"),n.style.display="none"):(h(o.hits),n.style.display=p>15?"block":"none")}catch{a.style.display="none",i("An error occurred. Please try again later.","error")}});n.addEventListener("click",async()=>{c+=1,a.style.display="block";try{const t=await m(d,c);a.style.display="none",t.hits.length===0||c*15>=p?(i("We're sorry, but you've reached the end of search results.","info"),n.style.display="none"):(h(t.hits),window.scrollBy({top:document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height*2,behavior:"smooth"}))}catch{a.style.display="none",i("An error occurred. Please try again later.","error")}});
//# sourceMappingURL=commonHelpers.js.map
